CREATE TABLE copytrading (
    user_id TEXT NOT NULL,
    bot_id INT NOT NULL,
    bot_name TEXT,
    bot_status TEXT,
    api_key_raw BYTEA,
    api_secret_raw BYTEA,
    exchange TEXT,
    binance_id TEXT,
    exc_spread_diff_percent NUMERIC,
    leverage NUMERIC,
    initial_open_percent NUMERIC,
    max_add_multiplier NUMERIC,
    open_delay NUMERIC,
    add_delay NUMERIC,
    one_coin_max_percent NUMERIC,
    blacklist_coins TEXT[],
    whitelist_coins TEXT[],
    add_prevention_percent NUMERIC,
    block_adds_above_entry BOOLEAN,
    max_open_positions INT,
    auto_tp NUMERIC,
    auto_sl NUMERIC,
    min_trader_size NUMERIC,
    test_mode BOOLEAN,
    notify_dest TEXT,
    mode_close_only BOOLEAN,
    mode_inverse BOOLEAN,
    mode_no_close BOOLEAN,
    mode_btc_trigger_price NUMERIC,
    mode_no_sells BOOLEAN,
    PRIMARY KEY (user_id, bot_id)
);